//
//  EmailProcessingService.swift
//  MindVault
//
//  Processes emails to build AI context with embeddings.
//  Handles content cleaning, metadata extraction, and vector storage.
//

import Foundation
import SwiftData

/// Service responsible for processing emails and preparing them for AI context
@MainActor
class EmailProcessingService: ObservableObject {
    
    // MARK: - Published Properties
    
    @Published var isProcessing: Bool = false
    @Published var processingProgress: Double = 0.0
    @Published var lastError: String?
    
    // MARK: - Private Properties
    
    private let modelContext: ModelContext
    private let embeddingService: EmbeddingService
    private let vectorDBService: VectorDBService
    
    // MARK: - Constants
    
    private enum Constants {
        static let maxContentLength = 5000
        static let maxKeywords = 10
        static let snippetLength = 300
    }
    
    // MARK: - Initialization
    
    init(modelContext: ModelContext) {
        self.modelContext = modelContext
        self.embeddingService = EmbeddingService.shared
        self.vectorDBService = VectorDBService.shared
    }
    
    // MARK: - Email Processing
    
    /// Process emails to extract meaningful content and create embeddings
    func processEmails(_ emails: [EmailMessage]) async throws {
        guard !emails.isEmpty else { return }
        
        isProcessing = true
        processingProgress = 0.0
        lastError = nil
        
        defer { isProcessing = false }
        
        for (index, email) in emails.enumerated() {
            do {
                try await processEmail(email)
                processingProgress = Double(index + 1) / Double(emails.count)
            } catch {
                print("Failed to process email \(email.id): \(error)")
                lastError = error.localizedDescription
            }
        }
    }
    
    public func processEmail(_ email: EmailMessage) async throws {
        // 1. Extract and clean content
        let cleanContent = cleanEmailContent(email)
        
        // 2. Extract metadata for context
        let metadata = extractMetadata(from: email)
        
        // 3. Create structured document for embedding
        let document = createDocument(from: email, cleanContent: cleanContent, metadata: metadata)
        
        // 4. Store in vector database (embedding is generated by the backend)
        try await vectorDBService.upsert(
            id: email.id.uuidString,
            content: document,
            type: "email",
            metadata: metadata
        )
        
        // 5. Mark email as processed
        email.isProcessedForAI = true
        try modelContext.save()
    }
    
    // MARK: - Content Cleaning
    
    /// Cleans email content by removing HTML, signatures, and quoted text
    /// - Parameter email: The email message to clean
    /// - Returns: Cleaned content suitable for AI processing
    private func cleanEmailContent(_ email: EmailMessage) -> String {
        var content = email.body
        
        // Remove HTML tags if needed
        if email.isHTML {
            content = stripHTMLTags(from: content)
        }
        
        // Remove email signatures
        content = removeSignature(from: content)
        
        // Remove quoted text (replies)
        content = removeQuotedText(from: content)
        
        // Remove excessive whitespace
        content = normalizeWhitespace(content)
        
        // Trim to reasonable length
        if content.count > Constants.maxContentLength {
            content = String(content.prefix(Constants.maxContentLength)) + "..."
        }
        
        return content
    }
    
    private func stripHTMLTags(from html: String) -> String {
        var result = html
        
        // Remove script and style tags with content
        result = result.replacingOccurrences(
            of: "<(script|style)[^>]*>[\\s\\S]*?</\\1>",
            with: "",
            options: .regularExpression
        )
        
        // Remove all HTML tags
        result = result.replacingOccurrences(
            of: "<[^>]+>",
            with: "",
            options: .regularExpression
        )
        
        // Decode HTML entities
        let entities = [
            ("&nbsp;", " "),
            ("&amp;", "&"),
            ("&lt;", "<"),
            ("&gt;", ">"),
            ("&quot;", "\""),
            ("&#39;", "'"),
            ("&apos;", "'")
        ]
        
        for (entity, replacement) in entities {
            result = result.replacingOccurrences(of: entity, with: replacement)
        }
        
        return result
    }
    
    private func removeSignature(from content: String) -> String {
        // Common signature patterns
        let signaturePatterns = [
            "^--\\s*$",
            "^Sent from my",
            "^Get Outlook for",
            "^Regards,",
            "^Best regards,",
            "^Best,",
            "^Thanks,",
            "^Thank you,"
        ]
        
        let lines = content.components(separatedBy: .newlines)
        var resultLines: [String] = []
        var foundSignature = false
        
        for line in lines {
            if !foundSignature {
                for pattern in signaturePatterns {
                    if line.range(of: pattern, options: [.regularExpression, .caseInsensitive]) != nil {
                        foundSignature = true
                        break
                    }
                }
                
                if !foundSignature {
                    resultLines.append(line)
                }
            }
        }
        
        return resultLines.joined(separator: "\n")
    }
    
    private func removeQuotedText(from content: String) -> String {
        let lines = content.components(separatedBy: .newlines)
        var resultLines: [String] = []
        
        for line in lines {
            // Skip lines that start with > (quoted text)
            if !line.trimmingCharacters(in: .whitespaces).hasPrefix(">") {
                resultLines.append(line)
            }
        }
        
        return resultLines.joined(separator: "\n")
    }
    
    private func normalizeWhitespace(_ content: String) -> String {
        // Replace multiple spaces with single space
        var result = content.replacingOccurrences(
            of: " +",
            with: " ",
            options: .regularExpression
        )
        
        // Replace multiple newlines with double newline
        result = result.replacingOccurrences(
            of: "\n{3,}",
            with: "\n\n",
            options: .regularExpression
        )
        
        return result.trimmingCharacters(in: .whitespacesAndNewlines)
    }
    
    // MARK: - Metadata Extraction
    
    private func extractMetadata(from email: EmailMessage) -> [String: String] {
        var metadata: [String: String] = [:]
        
        metadata["type"] = "email"
        metadata["subject"] = email.subject
        metadata["from"] = email.from
        metadata["from_name"] = email.fromName ?? ""
        metadata["date"] = ISO8601DateFormatter().string(from: email.date)
        metadata["message_id"] = email.messageId
        
        if let labels = email.labels {
            metadata["labels"] = labels.joined(separator: ", ")
        }
        
        if email.hasAttachments {
            metadata["has_attachments"] = "true"
            metadata["attachment_count"] = String(email.attachmentCount)
        }
        
        // Extract key topics/entities (simple keyword extraction)
        let keywords = extractKeywords(from: email.subject + " " + email.body)
        metadata["keywords"] = keywords.joined(separator: ", ")
        
        return metadata
    }
    
    private func extractKeywords(from text: String) -> [String] {
        // Simple keyword extraction based on word frequency
        // In production, you'd use NLP/NLU for better results
        
        let stopWords = Set([
            "the", "a", "an", "and", "or", "but", "in", "on", "at", "to", "for",
            "of", "with", "by", "from", "as", "is", "was", "are", "were", "be",
            "been", "being", "have", "has", "had", "do", "does", "did", "will",
            "would", "should", "could", "may", "might", "must", "can", "this",
            "that", "these", "those", "i", "you", "he", "she", "it", "we", "they"
        ])
        
        let words = text.lowercased()
            .components(separatedBy: .whitespacesAndNewlines)
            .map { $0.trimmingCharacters(in: .punctuationCharacters) }
            .filter { $0.count > 3 && !stopWords.contains($0) }
        
        // Count word frequency
        var wordCounts: [String: Int] = [:]
        for word in words {
            wordCounts[word, default: 0] += 1
        }
        
        // Return top keywords based on frequency
        return Array(wordCounts.sorted { $0.value > $1.value }
            .prefix(Constants.maxKeywords)
            .map { $0.key })
    }
    
    // MARK: - Document Creation
    
    private func createDocument(from email: EmailMessage, cleanContent: String, metadata: [String: String]) -> String {
        // Create a structured document with context
        var document = """
        EMAIL
        Subject: \(email.subject)
        From: \(email.fromName ?? email.from)
        Date: \(email.date.formatted(date: .long, time: .shortened))
        
        """
        
        if let labels = email.labels, !labels.isEmpty {
            document += "Labels: \(labels.joined(separator: ", "))\n\n"
        }
        
        document += "Content:\n\(cleanContent)"
        
        return document
    }
    
    // MARK: - Batch Processing
    
    func processUnprocessedEmails(for account: EmailAccount) async throws {
        // Fetch all email messages and filter in memory to avoid predicate macro issues
        let descriptor = FetchDescriptor<EmailMessage>()
        let allEmails = try modelContext.fetch(descriptor)
        
        // Filter for unprocessed emails from this account
        let unprocessedEmails = allEmails.filter { email in
            email.account?.id == account.id && !email.isProcessedForAI
        }
        
        if !unprocessedEmails.isEmpty {
            try await processEmails(unprocessedEmails)
        }
    }
    
    // MARK: - Search Context
    
    func buildSearchContext(for query: String, limit: Int = 5) async throws -> [EmailContext] {
        // Use vector database service to find relevant emails
        let results = try await vectorDBService.search(query: query, topK: limit)
        
        var contexts: [EmailContext] = []
        
        // Fetch all email messages once
        let descriptor = FetchDescriptor<EmailMessage>()
        let allEmails = (try? modelContext.fetch(descriptor)) ?? []
        
        for result in results {
            // Find the email by ID in memory (avoiding predicate macro issues)
            if let emailId = UUID(uuidString: result.id),
               let email = allEmails.first(where: { $0.id == emailId }) {
                let snippet = result.content?.prefix(Constants.snippetLength) ?? ""
                contexts.append(EmailContext(
                    email: email,
                    relevanceScore: Double(result.score),
                    snippet: String(snippet)
                ))
            }
        }
        
        return contexts
    }
}

// MARK: - Supporting Types

struct EmailContext {
    let email: EmailMessage
    let relevanceScore: Double
    let snippet: String
}
